name: tflite_flutter_custom
description: TensorFlow Lite Flutter plugin provides an easy, flexible, and fast Dart API to integrate TFLite models in flutter apps across mobile and desktop platforms.
version: 1.2.2
homepage: https://github.com/tensorflow/flutter-tflite

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=1.10.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1
  plugin_platform_interface: ^2.1.8
  quiver: ^3.2.2
  ffi: ^2.1.5

dev_dependencies:
  ffigen: ^10.0.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  melos: ^6.1.0
  test: ^1.6.4

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      macos: 
        ffiPlugin: true
      linux:
        ffiPlugin: true
      windows:
        ffiPlugin: true